server:
  port: 8080
#  servlet:
#    session:
#      timeout: 2m

spring:
  application:
    name: security-session
  datasource:
    url: jdbc:h2:mem:h2test;DB_CLOSE_DELAY=-1
    platform: h2
    driver-class-name: org.h2.Driver
    username: sa
    password:
    schema: classpath:h2/schema.sql
    data: classpath:h2/data.sql
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

  # 以 Redis 形式存储 session
  session:
#    timeout: 2m
    store-type: redis
  redis:
    host: 106.14.172.103


